const color = [
  { label: "AliceBlue", value: "aliceblue", color: "#f0f8ff" },
  { label: "AntiqueWhite", value: "antiquewhite", color: "#faebd7" },
  { label: "Aqua", value: "aqua", color: "#00ffff" },
  { label: "Aquamarine", value: "aquamarine", color: "#7fffd4" },
  { label: "Azure", value: "azure", color: "#f0ffff" },
  { label: "Beige", value: "beige", color: "#f5f5dc" },
  { label: "Bisque", value: "bisque", color: "#ffe4c4" },
  { label: "Black", value: "black", color: "#000000" },
  {
    label: "BlanchedAlmond",
    value: "blanchedalmond",
    color: "#ffebcd",
  },
  { label: "Blue", value: "blue", color: "#0000ff" },
  { label: "BlueViolet", value: "blueviolet", color: "#8a2be2" },
  { label: "Brown", value: "brown", color: "#a52a2a" },
  { label: "BurlyWood", value: "burlywood", color: "#deb887" },
  { label: "CadetBlue", value: "cadetblue", color: "#5f9ea0" },
  { label: "Chartreuse", value: "chartreuse", color: "#7fff00" },
  { label: "Chocolate", value: "chocolate", color: "#d2691e" },
  { label: "Coral", value: "coral", color: "#ff7f50" },
  {
    label: "CornflowerBlue",
    value: "cornflowerblue",
    color: "#6495ed",
  },
  { label: "Cornsilk", value: "cornsilk", color: "#fff8dc" },
  { label: "Crimson", value: "crimson", color: "#dc143c" },
  { label: "Cyan", value: "cyan", color: "#00ffff" },
  { label: "DarkBlue", value: "darkblue", color: "#00008b" },
  { label: "DarkCyan", value: "darkcyan", color: "#008b8b" },
  { label: "DarkGoldenRod", value: "darkgoldenrod", color: "#b8860b" },
  { label: "DarkGray", value: "darkgray", color: "#a9a9a9" },
  { label: "DarkGrey", value: "darkgrey", color: "#a9a9a9" },
  { label: "DarkGreen", value: "darkgreen", color: "#006400" },
  { label: "DarkKhaki", value: "darkkhaki", color: "#bdb76b" },
  { label: "DarkMagenta", value: "darkmagenta", color: "#8b008b" },
  {
    label: "DarkOliveGreen",
    value: "darkolivegreen",
    color: "#556b2f",
  },
  { label: "DarkOrange", value: "darkorange", color: "#ff8c00" },
  { label: "DarkOrchid", value: "darkorchid", color: "#9932cc" },
  { label: "DarkRed", value: "darkred", color: "#8b0000" },
  { label: "DarkSalmon", value: "darksalmon", color: "#e9967a" },
  { label: "DarkSeaGreen", value: "darkseagreen", color: "#8fbc8f" },
  { label: "DarkSlateBlue", value: "darkslateblue", color: "#483d8b" },
  { label: "DarkSlateGray", value: "darkslategray", color: "#2f4f4f" },
  { label: "DarkSlateGrey", value: "darkslategrey", color: "#2f4f4f" },
  { label: "DarkTurquoise", value: "darkturquoise", color: "#00ced1" },
  { label: "DarkViolet", value: "darkviolet", color: "#9400d3" },
  { label: "DeepPink", value: "deeppink", color: "#ff1493" },
  { label: "DeepSkyBlue", value: "deepskyblue", color: "#00bfff" },
  { label: "DimGray", value: "dimgray", color: "#696969" },
  { label: "DimGrey", value: "dimgrey", color: "#696969" },
  { label: "DodgerBlue", value: "dodgerblue", color: "#1e90ff" },
  { label: "FireBrick", value: "firebrick", color: "#b22222" },
  { label: "FloralWhite", value: "floralwhite", color: "#fffaf0" },
  { label: "ForestGreen", value: "forestgreen", color: "#228b22" },
  { label: "Fuchsia", value: "fuchsia", color: "#ff00ff" },
  { label: "Gainsboro", value: "gainsboro", color: "#dcdcdc" },
  { label: "GhostWhite", value: "ghostwhite", color: "#f8f8ff" },
  { label: "Gold", value: "gold", color: "#ffd700" },
  { label: "GoldenRod", value: "goldenrod", color: "#daa520" },
  { label: "Gray", value: "gray", color: "#808080" },
  { label: "Grey", value: "grey", color: "#808080" },
  { label: "Green", value: "green", color: "#008000" },
  { label: "GreenYellow", value: "greenyellow", color: "#adff2f" },
  { label: "HoneyDew", value: "honeydew", color: "#f0fff0" },
  { label: "HotPink", value: "hotpink", color: "#ff69b4" },
  { label: "IndianRed", value: "indianred", color: "#cd5c5c" },
  { label: "Indigo", value: "indigo", color: "#4b0082" },
  { label: "Ivory", value: "ivory", color: "#fffff0" },
  { label: "Khaki", value: "khaki", color: "#f0e68c" },
  { label: "Lavender", value: "lavender", color: "#e6e6fa" },
  { label: "LavenderBlush", value: "lavenderblush", color: "#fff0f5" },
  { label: "LawnGreen", value: "lawngreen", color: "#7cfc00" },
  { label: "LemonChiffon", value: "lemonchiffon", color: "#fffacd" },
  { label: "LightBlue", value: "lightblue", color: "#add8e6" },
  { label: "LightCoral", value: "lightcoral", color: "#f08080" },
  { label: "LightCyan", value: "lightcyan", color: "#e0ffff" },
  {
    label: "LightGoldenRodYellow",
    value: "lightgoldenrodyellow",
    color: "#fafad2",
  },
  { label: "LightGray", value: "lightgray", color: "#d3d3d3" },
  { label: "LightGrey", value: "lightgrey", color: "#d3d3d3" },
  { label: "LightGreen", value: "lightgreen", color: "#90ee90" },
  { label: "LightPink", value: "lightpink", color: "#ffb6c1" },
  { label: "LightSalmon", value: "lightsalmon", color: "#ffa07a" },
  { label: "LightSeaGreen", value: "lightseagreen", color: "#20b2aa" },
  { label: "LightSkyBlue", value: "lightskyblue", color: "#87cefa" },
  {
    label: "LightSlateGray",
    value: "lightslategray",
    color: "#778899",
  },
  {
    label: "LightSlateGrey",
    value: "lightslategrey",
    color: "#778899",
  },
  {
    label: "LightSteelBlue",
    value: "lightsteelblue",
    color: "#b0c4de",
  },
  { label: "LightYellow", value: "lightyellow", color: "#ffffe0" },
  { label: "Lime", value: "lime", color: "#00ff00" },
  { label: "LimeGreen", value: "limegreen", color: "#32cd32" },
  { label: "Linen", value: "linen", color: "#faf0e6" },
  { label: "Magenta", value: "magenta", color: "#ff00ff" },
  { label: "Maroon", value: "maroon", color: "#800000" },
  {
    label: "MediumAquaMarine",
    value: "mediumaquamarine",
    color: "#66cdaa",
  },
  { label: "MediumBlue", value: "mediumblue", color: "#0000cd" },
  { label: "MediumOrchid", value: "mediumorchid", color: "#ba55d3" },
  { label: "MediumPurple", value: "mediumpurple", color: "#9370d8" },
  {
    label: "MediumSeaGreen",
    value: "mediumseagreen",
    color: "#3cb371",
  },
  {
    label: "MediumSlateBlue",
    value: "mediumslateblue",
    color: "#7b68ee",
  },
  {
    label: "MediumSpringGreen",
    value: "mediumspringgreen",
    color: "#00fa9a",
  },
  {
    label: "MediumTurquoise",
    value: "mediumturquoise",
    color: "#48d1cc",
  },
  {
    label: "MediumVioletRed",
    value: "mediumvioletred",
    color: "#c71585",
  },
  { label: "MidnightBlue", value: "midnightblue", color: "#191970" },
  { label: "MintCream", value: "mintcream", color: "#f5fffa" },
  { label: "MistyRose", value: "mistyrose", color: "#ffe4e1" },
  { label: "Moccasin", value: "moccasin", color: "#ffe4b5" },
  { label: "NavajoWhite", value: "navajowhite", color: "#ffdead" },
  { label: "Navy", value: "navy", color: "#000080" },
  { label: "OldLace", value: "oldlace", color: "#fdf5e6" },
  { label: "Olive", value: "olive", color: "#808000" },
  { label: "OliveDrab", value: "olivedrab", color: "#6b8e23" },
  { label: "Orange", value: "orange", color: "#ffa500" },
  { label: "OrangeRed", value: "orangered", color: "#ff4500" },
  { label: "Orchid", value: "orchid", color: "#da70d6" },
  { label: "PaleGoldenRod", value: "palegoldenrod", color: "#eee8aa" },
  { label: "PaleGreen", value: "palegreen", color: "#98fb98" },
  { label: "PaleTurquoise", value: "paleturquoise", color: "#afeeee" },
  { label: "PaleVioletRed", value: "palevioletred", color: "#d87093" },
  { label: "PapayaWhip", value: "papayawhip", color: "#ffefd5" },
  { label: "PeachPuff", value: "peachpuff", color: "#ffdab9" },
  { label: "Peru", value: "peru", color: "#cd853f" },
  { label: "Pink", value: "pink", color: "#ffc0cb" },
  { label: "Plum", value: "plum", color: "#dda0dd" },
  { label: "PowderBlue", value: "powderblue", color: "#b0e0e6" },
  { label: "Purple", value: "purple", color: "#800080" },
  { label: "RebeccaPurple", value: "rebeccapurple", color: "#663399" },
  { label: "Red", value: "red", color: "#ff0000" },
  { label: "RosyBrown", value: "rosybrown", color: "#bc8f8f" },
  { label: "RoyalBlue", value: "royalblue", color: "#4169e1" },
  { label: "SaddleBrown", value: "saddlebrown", color: "#8b4513" },
  { label: "Salmon", value: "salmon", color: "#fa8072" },
  { label: "SandyBrown", value: "sandybrown", color: "#f4a460" },
  { label: "SeaGreen", value: "seagreen", color: "#2e8b57" },
  { label: "SeaShell", value: "seashell", color: "#fff5ee" },
  { label: "Sienna", value: "sienna", color: "#a0522d" },
  { label: "Silver", value: "silver", color: "#c0c0c0" },
  { label: "SkyBlue", value: "skyblue", color: "#87ceeb" },
  { label: "SlateBlue", value: "slateblue", color: "#6a5acd" },
  { label: "SlateGray", value: "slategray", color: "#708090" },
  { label: "SlateGrey", value: "slategrey", color: "#708090" },
  { label: "Snow", value: "snow", color: "#fffafa" },
  { label: "SpringGreen", value: "springgreen", color: "#00ff7f" },
  { label: "SteelBlue", value: "steelblue", color: "#4682b4" },
  { label: "Tan", value: "tan", color: "#d2b48c" },
  { label: "Teal", value: "teal", color: "#008080" },
  { label: "Thistle", value: "thistle", color: "#d8bfd8" },
  { label: "Tomato", value: "tomato", color: "#ff6347" },
  { label: "Turquoise", value: "turquoise", color: "#40e0d0" },
  { label: "Violet", value: "violet", color: "#ee82ee" },
  { label: "Wheat", value: "wheat", color: "#f5deb3" },
  { label: "White", value: "white", color: "#ffffff" },
  { label: "WhiteSmoke", value: "whitesmoke", color: "#f5f5f5" },
  { label: "Yellow", value: "yellow", color: "#ffff00" },
  { label: "YellowGreen", value: "yellowgreen", color: "#9acd32" },
];

export default color;
